services:
    nuxt-app:
        container_name: koroluk-nuxt-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../:/workspaces/app:cached
        env_file: ../.env
        command: sleep infinity # chill out a bit

    db:
        image: mysql:8.0
        env_file: ../.env
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    db_data:
        driver: local
